const API_URL = 'https://script.google.com/macros/s/AKfycbyQ7m1_V0MPBySvXy2NBTq-3L8wqd4jxOF_9jO2QbURBUm5mtCeksp7r7EEYp34oQgK/exec'; // Set this to your deployed Google Apps Script web app URL.
const BRANCHES = ['BNB Rosales branch', 'BNB Urdaneta branch', 'BNB Tayug branch', 'EZ San Carlos branch', 'EZ San Jose branch', '1LR Tarlac Branch'];
const WAREHOUSE = 'Warehouse';
const demoAccounts = [{name:'Technician', username:'technician', password:'demo123', role:'technician', branch:'All branches'}, {name:'Office coordinator', username:'office', password:'demo123', role:'office', branch:'All branches'}, {name:'Rosales admin', username:'rosales.admin', password:'demo123', role:'admin', branch:'BNB Rosales branch'}];
let currentUser = JSON.parse(localStorage.getItem('unitflowUser')) || null;
let units = JSON.parse(localStorage.getItem('unitflowUnits')) || [{unitCode:'UF-1048',clientName:'Northstar Foods',model:'Dell Latitude 5420',processor:'Intel Core i5',ram:'16 GB',storage:'512 GB SSD',status:'Released',currentLocation:'BNB Rosales branch',updated:'Today, 9:42 AM'},{unitCode:'UF-1047',clientName:'Mabini Pharmacy',model:'Lenovo ThinkPad E14',processor:'Intel Core i5',ram:'8 GB',storage:'256 GB SSD',status:'For observation',currentLocation:'EZ San Carlos branch',updated:'Yesterday'},{unitCode:'UF-1046',clientName:'Cedar & Co.',model:'HP ProDesk 400',processor:'Intel Core i3',ram:'8 GB',storage:'1 TB HDD',status:'For release',currentLocation:'BNB Urdaneta branch',updated:'Sep 7, 2026'},{unitCode:'UF-1045',clientName:'Ridgeway Hotel',model:'Acer Veriton',processor:'Intel Core i5',ram:'16 GB',storage:'512 GB SSD',status:'To be transfered',currentLocation:'1LR Tarlac Branch',updated:'Sep 6, 2026'},{unitCode:'UF-1044',clientName:'Sunline Market',model:'ASUS ExpertCenter',processor:'Intel Core i3',ram:'8 GB',storage:'500 GB HDD',status:'In warehouse',currentLocation:'EZ San Jose branch',updated:'Sep 5, 2026'}];
units = units.map(unit => unit.unitCode ? {...unit, unitPrice:Number(unit.unitPrice || 0), dateReceived:unit.dateReceived || '', releasedDate:unit.releasedDate || ''} : {unitCode:unit.id || 'Unassigned', clientName:unit.client || 'Unknown client', model:unit.type || 'Unspecified', processor:'Not recorded', ram:'Not recorded', storage:'Not recorded', unitPrice:0, status:'For observation', currentLocation:unit.branch || BRANCHES[0], dateReceived:'', releasedDate:'', updated:unit.updated || 'Previously recorded'});
let accounts = JSON.parse(localStorage.getItem('unitflowAccounts') || 'null') || [...demoAccounts];
let editingUnitCode = null;
let removedBranches = JSON.parse(localStorage.getItem('unitflowRemovedBranches') || '[]');
let branchNames = JSON.parse(localStorage.getItem('unitflowBranches') || 'null') || [...BRANCHES];
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value).replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const adminLocations = () => [...new Set([currentUser.branch, 'BNB Rosales branch', WAREHOUSE])];
const activeBranches = () => branchNames.filter(branch => !removedBranches.includes(branch));
const visibleUnits = () => currentUser.role === 'admin' ? units.filter(unit => adminLocations().includes(unit.currentLocation)) : units;
function statusBadge(status){return `<span class="badge badge-${status.toLowerCase().replace(/\s+/g,'-')}">${escapeHtml(status)}</span>`}
function specs(unit){return `${unit.processor}, ${unit.ram}, ${unit.storage}`}
function peso(value){return Number(value || 0).toLocaleString('en-PH',{style:'currency',currency:'PHP'})}
function displayDate(value){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?escapeHtml(value):date.toLocaleDateString('en-PH',{year:'numeric',month:'short',day:'numeric'})}
function dateInputValue(value){if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?String(value).slice(0,10):date.toISOString().slice(0,10)}
function render(){if(!currentUser)return;const shown=visibleUnits(); $('#loginScreen').classList.add('hidden'); $('.app-shell').classList.remove('hidden'); $('#userName').textContent=currentUser.name; $('#userRole').textContent=currentUser.role; $('#headingName').textContent=currentUser.name.split(' ')[0]; $('#totalUnits').textContent=shown.length; $('#activeUnits').textContent=shown.filter(unit=>unit.status==='Released').length; $('#attentionUnits').textContent=shown.filter(unit=>unit.status==='For observation').length; $('#branchCount').textContent=currentUser.role==='admin'?adminLocations().length:activeBranches().length; document.querySelectorAll('[data-management-view]').forEach(link=>link.classList.toggle('hidden',currentUser.role==='admin')); $('#addAccountButton').classList.toggle('hidden',currentUser.role!=='technician'); renderRecent(shown); renderAllUnits(shown); renderBranches(shown); renderAccounts(); populateBranchSelect();}
function renderRecent(shown){$('#recentUnits').innerHTML=shown.slice(0,5).map(unit=>`<tr><td><div class="unit-name">${escapeHtml(unit.unitCode)}</div></td><td>${escapeHtml(unit.clientName)}</td><td>${escapeHtml(unit.model)}</td><td>${peso(unit.unitPrice)}</td><td>${statusBadge(unit.status)}</td><td>${escapeHtml(unit.currentLocation)}</td><td>${displayDate(unit.dateReceived)}</td><td>${displayDate(unit.releasedDate)}</td></tr>`).join('') || '<tr><td colspan="8">No units found.</td></tr>'}
function renderAllUnits(shown=visibleUnits()){const query=($('#unitSearch')?.value||'').toLowerCase(); const filter=$('#statusFilter')?.value||'all'; const filtered=shown.filter(unit=>(filter==='all'||unit.status===filter)&&[unit.unitCode,unit.clientName,unit.model,specs(unit),unit.unitPrice,unit.status,unit.currentLocation,unit.dateReceived,unit.releasedDate].join(' ').toLowerCase().includes(query)); $('#allUnits').innerHTML=filtered.map(unit=>`<tr><td><strong>${escapeHtml(unit.unitCode)}</strong></td><td>${escapeHtml(unit.clientName)}</td><td>${escapeHtml(unit.model)}</td><td>${escapeHtml(unit.processor)}</td><td>${escapeHtml(unit.ram)}</td><td>${escapeHtml(unit.storage)}</td><td>${peso(unit.unitPrice)}</td><td>${statusBadge(unit.status)}</td><td>${escapeHtml(unit.currentLocation)}</td><td>${displayDate(unit.dateReceived)}</td><td>${displayDate(unit.releasedDate)}</td><td><div class="action-buttons"><button class="icon-button" title="Edit unit" data-edit-unit="${escapeHtml(unit.unitCode)}">⋯</button>${currentUser.role==='technician'?`<button class="delete-button" aria-label="Delete unit ${escapeHtml(unit.unitCode)}" title="Delete unit" data-delete-unit="${escapeHtml(unit.unitCode)}">&#128465;</button>`:''}</div></td></tr>`).join('') || '<tr><td colspan="12">No matching units found.</td></tr>'}
function renderBranches(shown){const counts=activeBranches().map(branch=>({branch,count:shown.filter(unit=>unit.currentLocation===branch).length})); const max=Math.max(...counts.map(item=>item.count),1); $('#branchPulse').innerHTML=counts.map(item=>`<div class="branch-row"><span class="branch-name">${escapeHtml(item.branch)}</span><span class="branch-count">${item.count} ${item.count===1?'unit':'units'}</span><span></span><div class="bar-track"><div class="bar-fill" style="width:${item.count/max*100}%"></div></div></div>`).join(''); $('#branchCards').innerHTML=counts.map(item=>`<article class="branch-card"><div class="branch-card-top"><div><h3>${escapeHtml(item.branch)}</h3><p>Unit tracking location</p></div><span class="stat-symbol green">⌁</span></div><div class="big-number">${item.count}</div><div class="branch-card-footer"><span>${item.count===1?'unit':'units'} currently registered</span>${currentUser.role==='technician'?`<button class="delete-button" aria-label="Delete branch ${escapeHtml(item.branch)}" title="Delete branch" data-delete-branch="${escapeHtml(item.branch)}">&#128465;</button>`:''}</div></article>`).join('')}
function renderAccounts(){$('#accountsTable').innerHTML=accounts.map(account=>`<tr><td><strong>${escapeHtml(account.name)}</strong></td><td>${escapeHtml(account.username)}</td><td>${escapeHtml(account.role)}</td><td>${escapeHtml(account.branch)}</td><td>${statusBadge('Active')}</td><td>${currentUser.role==='technician'?'<button class="icon-button" title="Account actions">⋯</button>':''}</td></tr>`).join('')}
function populateBranchSelect(){$('#unitBranch').innerHTML=(currentUser.role==='admin'?adminLocations():[...activeBranches(),WAREHOUSE]).map(branch=>`<option>${escapeHtml(branch)}</option>`).join('');$('#accountBranch').innerHTML=['All branches',...activeBranches()].map(branch=>`<option>${escapeHtml(branch)}</option>`).join('')}
function showView(view){if(currentUser.role==='admin'&&(view==='branches'||view==='accounts')){toast('This view is available to technician and office accounts.');return}document.querySelectorAll('.page-view').forEach(element=>element.classList.add('hidden')); $(`#${view}View`).classList.remove('hidden'); document.querySelectorAll('.nav-link').forEach(link=>link.classList.toggle('active',link.dataset.view===view)); $('#breadcrumbLabel').textContent=view[0].toUpperCase()+view.slice(1); if(view==='units')renderAllUnits(); if(window.innerWidth<701)$('#mobileMenu').click()}
function toast(message){const element=$('#toast'); element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),2600)}
function openModal(unit=null){editingUnitCode=unit?.unitCode||null;populateBranchSelect();const form=$('#unitForm');form.reset();$('#unitModalTitle').textContent=editingUnitCode?'Edit unit':'Register a unit';$('#unitModalCopy').textContent=editingUnitCode?'Update this unit in your permitted branch data.':'Add a client unit to the shared tracking database.';$('#unitSubmitButton').textContent=editingUnitCode?'Update unit':'Save unit';if(unit)Object.entries(unit).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=key==='dateReceived'||key==='releasedDate'?dateInputValue(value):value ?? ''});$('#unitModal').classList.remove('hidden');form.querySelector('input').focus()}
function openAccountModal(){if(currentUser.role!=='technician')return;populateBranchSelect();$('#accountForm').reset();$('#accountModal').classList.remove('hidden');$('#accountForm').elements.name.focus()}
function openBranchModal(){if(!['technician','office'].includes(currentUser.role))return;$('#branchForm').reset();$('#branchModal').classList.remove('hidden');$('#branchForm').elements.name.focus()}
function editUnit(unitCode){const unit=visibleUnits().find(item=>item.unitCode===unitCode);if(unit)openModal(unit);}
async function deleteUnit(unitCode){if(currentUser.role!=='technician'||!window.confirm(`Delete unit ${unitCode}?`))return;units=units.filter(unit=>unit.unitCode!==unitCode);localStorage.setItem('unitflowUnits',JSON.stringify(units));if(API_URL)await apiRequest('deleteUnit',{unitCode});render();toast('Unit deleted.');}
async function deleteBranch(branch){if(currentUser.role!=='technician'||!window.confirm(`Delete ${branch}?`))return;removedBranches=[...removedBranches,branch];localStorage.setItem('unitflowRemovedBranches',JSON.stringify(removedBranches));if(API_URL)await apiRequest('deleteBranch',{name:branch});render();toast('Branch deleted.');}
document.querySelectorAll('[data-view]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();showView(link.dataset.view)}));
$('#togglePassword').addEventListener('click',()=>{const input=document.querySelector('[name=password]');input.type=input.type==='password'?'text':'password';$('#togglePassword').textContent=input.type==='password'?'Show':'Hide'});
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.target));let account;if(API_URL){const result=await apiRequest('login',form);if(!result?.ok){$('#loginError').textContent=result?.error||'Unable to sign in';return}account=result.user;localStorage.setItem('unitflowToken',result.token)}else account=demoAccounts.find(item=>item.username===form.username&&item.password===form.password);if(!account){$('#loginError').textContent='Invalid username or password';return}currentUser=account;localStorage.setItem('unitflowUser',JSON.stringify(account));$('#loginError').textContent='';render();});
function signOut(){localStorage.removeItem('unitflowUser');localStorage.removeItem('unitflowToken');currentUser=null;editingUnitCode=null;$('#unitModal').classList.add('hidden');$('.app-shell').classList.add('hidden');$('#loginScreen').classList.remove('hidden');$('#loginForm').reset();$('#loginError').textContent='';window.scrollTo(0,0)}
$('#newUnitButton').addEventListener('click',openModal);$('#newUnitButtonSecondary').addEventListener('click',openModal);$('#addBranchButton').addEventListener('click',openBranchModal);$('#addAccountButton').addEventListener('click',openAccountModal);document.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',event=>$(event.currentTarget.dataset.closeModal).classList.add('hidden')));$('#unitSearch').addEventListener('input',()=>renderAllUnits());$('#statusFilter').addEventListener('change',()=>renderAllUnits());$('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$('#logoutButton').addEventListener('click',signOut);
$('#accountForm').addEventListener('submit',async event=>{event.preventDefault();const account=Object.fromEntries(new FormData(event.target));if(accounts.some(item=>item.username===account.username)){toast('That username already exists.');return}accounts.push({...account,status:'Active'});localStorage.setItem('unitflowAccounts',JSON.stringify(accounts));if(API_URL)await apiRequest('createAccount',account);$('#accountModal').classList.add('hidden');event.target.reset();renderAccounts();toast('Account created successfully.');});
$('#branchForm').addEventListener('submit',async event=>{event.preventDefault();const name=new FormData(event.target).get('name').trim();if(!name||branchNames.includes(name)){toast('Enter a new branch name.');return}branchNames.push(name);removedBranches=removedBranches.filter(branch=>branch!==name);localStorage.setItem('unitflowBranches',JSON.stringify(branchNames));localStorage.setItem('unitflowRemovedBranches',JSON.stringify(removedBranches));if(API_URL)await apiRequest('createBranch',{name});$('#branchModal').classList.add('hidden');event.target.reset();render();toast('Branch added successfully.');});
$('#unitForm').addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));const unit={unitCode:data.unitCode,clientName:data.clientName,model:data.model,processor:data.processor,ram:data.ram,storage:data.storage,unitPrice:Number(data.unitPrice),status:data.status,currentLocation:data.currentLocation,dateReceived:data.dateReceived,releasedDate:data.releasedDate,updated:'Just now',notes:data.notes};if(editingUnitCode){const existing=visibleUnits().find(item=>item.unitCode===editingUnitCode);if(!existing)return;units=units.map(item=>item.unitCode===editingUnitCode?unit:item);toast('Unit updated successfully.');if(API_URL)await apiRequest('updateUnit',{originalUnitCode:editingUnitCode,...unit})}else{units=[unit,...units];toast('Unit registered and saved locally.');if(API_URL)await apiRequest('createUnit',unit)}localStorage.setItem('unitflowUnits',JSON.stringify(units));editingUnitCode=null;$('#unitModal').classList.add('hidden');event.target.reset();render();});
document.addEventListener('click',event=>{const edit=event.target.closest('[data-edit-unit]');if(edit){editUnit(edit.dataset.editUnit);return}const unit=event.target.closest('[data-delete-unit]');if(unit){deleteUnit(unit.dataset.deleteUnit);return}const branch=event.target.closest('[data-delete-branch]');if(branch)deleteBranch(branch.dataset.deleteBranch)});
async function apiRequest(action,payload={}){try{const response=await fetch(API_URL,{method:'POST',body:JSON.stringify({action,...payload})});if(!response.ok)throw new Error(`Google Sheets returned HTTP ${response.status}`);const text=await response.text();try{return JSON.parse(text)}catch(error){throw new Error('Google Sheets returned an invalid response')}}catch(error){toast(error.message||'Could not reach Google Sheets right now.');return {ok:false,error:error.message}}}
render();